[package]
name = "ray_trace_weekend"
version = "0.1.0"
authors = ["spillow <scott.pillow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
